/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author pdavila
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1Content = new javax.swing.JTabbedPane();
        jPanelProduct = new javax.swing.JPanel();
        jScrollPaneProduct = new javax.swing.JScrollPane();
        jTableProduct = new javax.swing.JTable();
        jLabelProductId = new javax.swing.JLabel();
        jLabelProductName = new javax.swing.JLabel();
        jLabelProductTraceMark = new javax.swing.JLabel();
        jLabelProductModel = new javax.swing.JLabel();
        jLabelProductPrice = new javax.swing.JLabel();
        jLabelProductStock = new javax.swing.JLabel();
        jTextFieldProductId = new javax.swing.JTextField();
        jTextFieldProductName = new javax.swing.JTextField();
        jTextFieldProductTraceMark = new javax.swing.JTextField();
        jTextFieldProductModel = new javax.swing.JTextField();
        jTextFieldProductPrice = new javax.swing.JTextField();
        jPanelProductButtons = new javax.swing.JPanel();
        jButtonProductCreate = new javax.swing.JButton();
        jButtonProductModify = new javax.swing.JButton();
        jButtonProductDelete = new javax.swing.JButton();
        jButtonProductClear = new javax.swing.JButton();
        jComboBoxProductStock = new javax.swing.JComboBox<>();
        jPanelStock = new javax.swing.JPanel();
        jScrollPaneStock = new javax.swing.JScrollPane();
        jTableStock = new javax.swing.JTable();
        jLabelStockId = new javax.swing.JLabel();
        jTextFieldStockId = new javax.swing.JTextField();
        jLabelStockTotal = new javax.swing.JLabel();
        jTextFieldStockTotal = new javax.swing.JTextField();
        jPanelStockButtons = new javax.swing.JPanel();
        jButtonStockCreate = new javax.swing.JButton();
        jButtonStockModify = new javax.swing.JButton();
        jButtonStockDelete = new javax.swing.JButton();
        jButtonStockClear = new javax.swing.JButton();
        jPanelCategory = new javax.swing.JPanel();
        jScrollPaneCategory = new javax.swing.JScrollPane();
        jTableCategory = new javax.swing.JTable();
        jLabelTitle = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneProduct.setViewportView(jTableProduct);

        jLabelProductId.setText("Identificador");

        jLabelProductName.setText("Nombre");

        jLabelProductTraceMark.setText("Marca");

        jLabelProductModel.setText("Modelo");

        jLabelProductPrice.setText("Precio");

        jLabelProductStock.setText("Stock");

        jTextFieldProductId.setEnabled(false);

        jButtonProductCreate.setText("Crear");

        jButtonProductModify.setText("Modificar");

        jButtonProductDelete.setText("Eliminar");

        jButtonProductClear.setText("Limpiar");

        javax.swing.GroupLayout jPanelProductButtonsLayout = new javax.swing.GroupLayout(jPanelProductButtons);
        jPanelProductButtons.setLayout(jPanelProductButtonsLayout);
        jPanelProductButtonsLayout.setHorizontalGroup(
            jPanelProductButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonProductClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonProductCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonProductModify, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jButtonProductDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelProductButtonsLayout.setVerticalGroup(
            jPanelProductButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProductButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonProductCreate)
                .addGap(18, 18, 18)
                .addComponent(jButtonProductModify)
                .addGap(18, 18, 18)
                .addComponent(jButtonProductDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jButtonProductClear)
                .addContainerGap())
        );

        jComboBoxProductStock.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "null" }));

        javax.swing.GroupLayout jPanelProductLayout = new javax.swing.GroupLayout(jPanelProduct);
        jPanelProduct.setLayout(jPanelProductLayout);
        jPanelProductLayout.setHorizontalGroup(
            jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductLayout.createSequentialGroup()
                .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelProductLayout.createSequentialGroup()
                        .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelProductLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabelProductModel))
                            .addGroup(jPanelProductLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelProductId)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelProductLayout.createSequentialGroup()
                                .addComponent(jTextFieldProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(131, 131, 131)
                                .addComponent(jLabelProductName))
                            .addGroup(jPanelProductLayout.createSequentialGroup()
                                .addComponent(jTextFieldProductModel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelProductPrice)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelProductLayout.createSequentialGroup()
                                .addComponent(jTextFieldProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelProductStock))
                            .addGroup(jPanelProductLayout.createSequentialGroup()
                                .addComponent(jTextFieldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(jLabelProductTraceMark)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldProductTraceMark, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jComboBoxProductStock, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPaneProduct))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanelProductButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelProductLayout.setVerticalGroup(
            jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductLayout.createSequentialGroup()
                .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanelProductButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelProductId)
                        .addComponent(jTextFieldProductId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelProductName)
                        .addComponent(jTextFieldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelProductTraceMark)
                        .addComponent(jTextFieldProductTraceMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelProductModel)
                        .addComponent(jLabelProductPrice)
                        .addComponent(jTextFieldProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelProductStock)
                        .addComponent(jComboBoxProductStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldProductModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1Content.addTab("Productos", jPanelProduct);

        jTableStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneStock.setViewportView(jTableStock);

        jLabelStockId.setText("Identificador");

        jTextFieldStockId.setEnabled(false);

        jLabelStockTotal.setText("Total");

        jButtonStockCreate.setText("Crear");

        jButtonStockModify.setText("Modificar");

        jButtonStockDelete.setText("Eliminar");

        jButtonStockClear.setText("Limpiar");

        javax.swing.GroupLayout jPanelStockButtonsLayout = new javax.swing.GroupLayout(jPanelStockButtons);
        jPanelStockButtons.setLayout(jPanelStockButtonsLayout);
        jPanelStockButtonsLayout.setHorizontalGroup(
            jPanelStockButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStockButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStockButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonStockCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonStockModify, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jButtonStockDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonStockClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelStockButtonsLayout.setVerticalGroup(
            jPanelStockButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStockButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonStockCreate)
                .addGap(18, 18, 18)
                .addComponent(jButtonStockModify)
                .addGap(18, 18, 18)
                .addComponent(jButtonStockDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jButtonStockClear)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelStockLayout = new javax.swing.GroupLayout(jPanelStock);
        jPanelStock.setLayout(jPanelStockLayout);
        jPanelStockLayout.setHorizontalGroup(
            jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStockLayout.createSequentialGroup()
                .addGroup(jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStockLayout.createSequentialGroup()
                        .addComponent(jScrollPaneStock, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelStockButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelStockLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelStockId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldStockId, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(jLabelStockTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldStockTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelStockLayout.setVerticalGroup(
            jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStockLayout.createSequentialGroup()
                .addGroup(jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneStock, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanelStockButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStockId)
                    .addComponent(jTextFieldStockId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldStockTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStockTotal))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1Content.addTab("Stock", jPanelStock);

        jTableCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneCategory.setViewportView(jTableCategory);

        javax.swing.GroupLayout jPanelCategoryLayout = new javax.swing.GroupLayout(jPanelCategory);
        jPanelCategory.setLayout(jPanelCategoryLayout);
        jPanelCategoryLayout.setHorizontalGroup(
            jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoryLayout.createSequentialGroup()
                .addComponent(jScrollPaneCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 166, Short.MAX_VALUE))
        );
        jPanelCategoryLayout.setVerticalGroup(
            jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoryLayout.createSequentialGroup()
                .addComponent(jScrollPaneCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 103, Short.MAX_VALUE))
        );

        jTabbedPane1Content.addTab("Category", jPanelCategory);

        jLabelTitle.setText("VENTAS");

        exitButton.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1Content))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(446, 446, 446)
                        .addComponent(jLabelTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1Content, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }
    
    public JButton getCreateProductButton() { return jButtonProductCreate; }
    public JButton getDeleteProductButton() { return jButtonProductDelete; }   
    public JButton getModifyProductButton() { return jButtonProductModify; } 
    public JButton getClearProductButton() { return jButtonProductClear; }
    public JButton getCreateStockButton() { return jButtonStockCreate; }
    public JButton getDeleteStockButton() { return jButtonStockDelete; }   
    public JButton getModifyStockButton() { return jButtonStockModify; } 
    public JButton getClearStockButton() { return jButtonStockClear; }
    
    public JButton getExitButton() { return exitButton; }
 
    public JLabel getTitleLabel() { return jLabelTitle; }
 
    public JLabel getProductIdLabel() { return jLabelProductId; }
    public JLabel getProductNameLabel() { return jLabelProductName; }
    public JLabel getProductTraceMarkLabel() { return jLabelProductTraceMark; }
    public JLabel getProductModelLabel() { return jLabelProductModel; }
    public JLabel getProductPriceLabel() { return jLabelProductPrice; }
    public JLabel getProductStockLabel() { return jLabelProductStock; }
    public JLabel getStockIdLabel() { return jLabelStockId; }
    public JLabel getStockTotal() { return jLabelStockTotal; }
     
    public JPanel getProductButtonsPanel() { return jPanelProductButtons; }
    public JPanel getStockButtonsPanel() { return jPanelStockButtons; }
    
    public JPanel getProductProductPanel() { return jPanelProduct; }
    public JPanel getStockPanel() { return jPanelStock; }
    
    public JScrollPane getProductPanel() { return jScrollPaneProduct; }
    public JScrollPane getStockStockPanel() { return jScrollPaneStock; }
    
    public JTable getProductTable() { return jTableProduct; }
    public JTable getStockTable() { return jTableStock; }
    
    public JTextField getProductIdTextField() { return jTextFieldProductId; }
    public JTextField getProductNameTextField() { return jTextFieldProductName; }
    public JTextField getProductTraceMarkTextField() { return jTextFieldProductTraceMark; }
    public JTextField getProductModelTextField() { return jTextFieldProductModel; }    
    public JTextField getProductPriceTextField() { return jTextFieldProductPrice; }
    //public JTextField getProductStockTextField() { return jTextFieldProductStock; }
    public JTextField getStockIdTextField() { return jTextFieldStockId; }
    public JTextField getStockTotalTextField() { return jTextFieldStockTotal; }
    
    public JComboBox getProductStockComboBox() { return jComboBoxProductStock; }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JButton jButtonProductClear;
    public javax.swing.JButton jButtonProductCreate;
    private javax.swing.JButton jButtonProductDelete;
    private javax.swing.JButton jButtonProductModify;
    private javax.swing.JButton jButtonStockClear;
    private javax.swing.JButton jButtonStockCreate;
    private javax.swing.JButton jButtonStockDelete;
    private javax.swing.JButton jButtonStockModify;
    private javax.swing.JComboBox<String> jComboBoxProductStock;
    private javax.swing.JLabel jLabelProductId;
    private javax.swing.JLabel jLabelProductModel;
    private javax.swing.JLabel jLabelProductName;
    private javax.swing.JLabel jLabelProductPrice;
    private javax.swing.JLabel jLabelProductStock;
    private javax.swing.JLabel jLabelProductTraceMark;
    private javax.swing.JLabel jLabelStockId;
    private javax.swing.JLabel jLabelStockTotal;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelCategory;
    private javax.swing.JPanel jPanelProduct;
    private javax.swing.JPanel jPanelProductButtons;
    private javax.swing.JPanel jPanelStock;
    private javax.swing.JPanel jPanelStockButtons;
    private javax.swing.JScrollPane jScrollPaneCategory;
    private javax.swing.JScrollPane jScrollPaneProduct;
    private javax.swing.JScrollPane jScrollPaneStock;
    private javax.swing.JTabbedPane jTabbedPane1Content;
    private javax.swing.JTable jTableCategory;
    private javax.swing.JTable jTableProduct;
    private javax.swing.JTable jTableStock;
    private javax.swing.JTextField jTextFieldProductId;
    private javax.swing.JTextField jTextFieldProductModel;
    private javax.swing.JTextField jTextFieldProductName;
    private javax.swing.JTextField jTextFieldProductPrice;
    private javax.swing.JTextField jTextFieldProductTraceMark;
    private javax.swing.JTextField jTextFieldStockId;
    private javax.swing.JTextField jTextFieldStockTotal;
    // End of variables declaration//GEN-END:variables
}
